"""add_priority_category

Revision ID: 76cfff517d0d
Revises: 5240e1f7c552
Create Date: 2026-01-27 20:16:08.255409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76cfff517d0d'
down_revision: Union[str, Sequence[str], None] = '5240e1f7c552'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emails', sa.Column('priority', sa.String(), nullable=True))
    op.add_column('emails', sa.Column('category', sa.String(), nullable=True))
    op.create_index(op.f('ix_emails_category'), 'emails', ['category'], unique=False)
    op.create_index(op.f('ix_emails_priority'), 'emails', ['priority'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_emails_priority'), table_name='emails')
    op.drop_index(op.f('ix_emails_category'), table_name='emails')
    op.drop_column('emails', 'category')
    op.drop_column('emails', 'priority')
    # ### end Alembic commands ###
