"""Add extracted features to Email

Revision ID: ae2c30622bdb
Revises: bb89e3ec0cdf
Create Date: 2026-01-26 08:13:29.417353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae2c30622bdb'
down_revision: Union[str, Sequence[str], None] = 'bb89e3ec0cdf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emails', sa.Column('event_title', sa.String(), nullable=True))
    op.add_column('emails', sa.Column('event_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('emails', sa.Column('deadline', sa.DateTime(timezone=True), nullable=True))
    op.add_column('emails', sa.Column('action_required', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('emails', 'action_required')
    op.drop_column('emails', 'deadline')
    op.drop_column('emails', 'event_date')
    op.drop_column('emails', 'event_title')
    # ### end Alembic commands ###
