"""add_last_synced_at_to_user

Revision ID: d6a7fa3d30c1
Revises: 76cfff517d0d
Create Date: 2026-01-28 20:54:55.098163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6a7fa3d30c1'
down_revision: Union[str, Sequence[str], None] = '76cfff517d0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_synced_at')
    # ### end Alembic commands ###
